###############################################################################
# If you like the plugin, don't forget to leave positive reviews and like it. #
# By doing so you help to promote this plugin                                 #
###############################################################################

enable-actionbar-pose: true
enable-change-armorstand-perm: false
disable-interact-armorstand-with-no-perm: false
enable-blacklist-worlds: false

blacklist-worlds: ["world"]

worldguard:
  enable-worldguard: false
  armorstand-interact-disable-flad-id: "armorstand-interact-disable"

messages:
  action-bar-message: "&6Pose: "
  change-pose-perm: "net.change.pose.perm"
  not-have-perm: "&4You don't have enough rights to do this!"
  disable-in-world: "&4In this world, it is forbidden to change poses at the armor stand!"
  worldguard-interact-disable: "&4Interactions with the armor stand, are not allowed in this region."

# You can add new poses!
armor:
  standPose:
    1:
      bodyPose: [0, 0, 0]
      headPose: [0, 0, 0]
      leftLegPose: [0, 0, 0]
      rightLegPose: [0, 0, 0]
      leftArmPose: [339, 0, 346]
      rightArmPose: [339, 0, 15]
    2:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 0 ]
      rightArmPose: [ 0, 0, 0 ]
    3:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 312, 0, 39 ]
      rightArmPose: [ 312, 0, 323 ]
    4:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 356, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 343 ]
      rightArmPose: [ 282, 0, 0 ]
    5:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 31, 0, 353 ]
      rightArmPose: [ 248, 37, 0 ]
    6:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 254, 37, 0 ]
      rightArmPose: [ 254, 324, 0 ]
    7:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 0, 0 ]
      leftLegPose: [ 11, 0, 353 ]
      rightLegPose: [ 0, 0, 8 ]
      leftArmPose: [ 254, 341, 0 ]
      rightArmPose: [ 241, 40, 0 ]
    8:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 0, 0, 0 ]
      leftLegPose: [ 0, 0, 0 ]
      rightLegPose: [ 0, 0, 0 ]
      leftArmPose: [ 0, 0, 346 ]
      rightArmPose: [ 309, 338, 15 ]
    9:
      bodyPose: [ 0, 6, 0 ]
      headPose: [ 356, 47, 0 ]
      leftLegPose: [ 0, 40, 350 ]
      rightLegPose: [ 0, 304, 0 ]
      leftArmPose: [ 18, 0, 353 ]
      rightArmPose: [ 248, 47, 0 ]
    10:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 14, 23, 0 ]
      leftLegPose: [ 18, 141, 350 ]
      rightLegPose: [ 349, 108, 0 ]
      leftArmPose: [ 0, 0, 225 ]
      rightArmPose: [ 265, 334, 0 ]
    11:
      bodyPose: [ 0, 0, 0 ]
      headPose: [ 346, 348, 0 ]
      leftLegPose: [ 0, 0, 353 ]
      rightLegPose: [ 315, 0, 0 ]
      leftArmPose: [ 268, 13, 225 ]
      rightArmPose: [ 268, 348, 0 ]
    12:
      bodyPose: [ 0, 355, 0 ]
      headPose: [ 356, 30, 0 ]
      leftLegPose: [ 238, 0, 306 ]
      rightLegPose: [ 349, 33, 343 ]
      leftArmPose: [ 0, 0, 242 ]
      rightArmPose: [ 0, 0, 120 ]
    13:
      bodyPose: [ 0, 351, 0 ]
      headPose: [ 356, 324, 0 ]
      leftLegPose: [ 346, 0, 12 ]
      rightLegPose: [ 248, 324, 343 ]
      leftArmPose: [ 0, 0, 242 ]
      rightArmPose: [ 0, 0, 120 ]