name: SimpleArmorStandPose
version: '${project.version}'
main: net.simple.armor.stand.pose.ArmorStandPose
api-version: 1.13
authors: [ KessPenGames ]
description: Plugin for pose armor stand

softdepend:
  - LWC