name: SimpleArmorStandPose
version: '${project.version}'
main: net.simple.armor.stand.pose.ArmorStandPosePlugin
api-version: 1.13
authors: [ No_KessPen ]
description: Plugin for pose armor stand
softdepend:
  - WorldGuard
